list1=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]
tuple1=("sunday","monday","tuesday","wednesday","thursday","friday","saturday")
dict1={
    1:"sunday",
    2:"monday",
    3:"tuesday",
    4:"wednesday",
    5:"thursday",
    6:"friday",
    7:"saturday"
    }
set1={"sunday","monday","tuesday","wednesday","thursday","friday","saturday"}
print(list1)
print(tuple1)
print(dict1)
print(set1)